[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
 
[project]
name = "MTensor"
version = "0.2.0"
description= "M-Tensor formalism implementation"
readme="README.md"
requires-python= ">=3.10"
license={text= "MIT"}
authors=[{name="Remi Cloarec", email="remi.cloarec@ensam.eu"}]
dependencies = ["numpy", "scipy"]
